#
# Build
#
FROM golang:1.23 AS builder

ENV CGO_ENABLED=0
ENV GOOS=linux
WORKDIR /build

COPY . .

RUN go build -o main ./server_a

#
# Deploy
#
FROM gcr.io/distroless/static-debian12:latest

WORKDIR /

COPY --from=builder /build/main /app/main_a

USER nonroot

CMD [ "/app/main_a" ]
